<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet package information -->
    <PackageId>DotNetRunCmd</PackageId>
    <Version>1.1.0</Version>
    <Authors>tifish</Authors>
    <Company></Company>
    <Description>A utility library for writing C# scripts as easily as batch (`.bat`) files.</Description>
    <PackageTags>dotnet;cs;script</PackageTags>
    <RepositoryUrl>https://github.com/tifish/DotNetRunCmd</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Optional but very common -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <!-- Add README.md to the package -->
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
