<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet package information -->
    <PackageId>DotNetRunCmd</PackageId>
    <Version>1.0.0</Version>
    <Authors>tifish</Authors>
    <Company></Company>
    <Description>Help to write file-based .cs like script.</Description>
    <PackageTags>dotnet;cs;script</PackageTags>
    <RepositoryUrl>https://github.com/tifish/DotNetRunCmd</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- Optional but very common -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
